eclipse-che4z/che-che4z-explorer-for-endevor

- CONTRIBUTING
- NOTICE
Final files needed for the open sourcing
> Adding CONTRIBUTING and NOTICE files

- Readme.md
Signed-off-by: Alexandru-Paul Dumitru <alexandru.dumitru@broadcom.com>
> remove outstanding gifs

- .gitignore
- src/EndevorController.ts
- src/commands/HostDialogs.ts
- src/service/SettingsFacade.ts
Added changes for this PR:
- Settings update are added in the Global Configuration
- Call for addSesssion is also added in loadRepositories()
- Add the logs folder in .gitignore
Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>
> Fix Issue 42: Loads the connection that is found in settings.json

- Readme.md
Signed-off-by: Zachariah Mullen <zachariah.mullen@broadcom.com>
I've added a couple of options under prerequisites and also added a few details about managing profiles via the Zowe CLI.
> Update prerequisites and profiles sections

- CHANGELOG.md
- package.json
Signed-off-by: Zachariah Mullen <zachariah.mullen@broadcom.com>
> Update for 0.10.1 fix version

- CHANGELOG.md
- package.json
Signed-off-by: Zachariah Mullen <zachariah.mullen@broadcom.com>
> Fix Version again

- .github/workflows/Explorer-for-Endevor-CI.yml
- test/runTest.ts
Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>
Steps included in the CI:
1. Check-out
2. Install
3. Pre-Publish
4. Audit
5. Run Tests
Tested OR: Windows, Ubuntu and MacOS (Latest)
Tested NodeJS: 10 and 12
Tested branches: Master and Development
> Feat: Github actions for CI

- __mocks__/vscode.ts
- package-lock.json
- package.json
- src/EndevorController.ts
Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>
Fix for issue #57
> Fix for issue 57

- package-lock.json
- package.json
- packages/explorer-for-endevor/.vscodeignore
- yarn.lock
Signed-off-by: Nikolai Imbirev <nikolay.imbirev@broadcom.com>
> Move documentation, lisence, notice & images into packaged vsix

- packages/explorer-for-endevor/package.json
Signed-off-by: Nikolai Imbirev <nikolay.imbirev@broadcom.com>
> Specify vsix file version during packaging

- CHANGELOG.md
- package.json
- packages/endevor/endevor.ts
- packages/explorer-for-endevor/package.json
- packages/explorer-for-endevor/src/commands/addNewElementLocation.ts
- packages/explorer-for-endevor/src/dialogs/locations/endevorServiceDialogs.ts
Signed-off-by: Vit Gottwald <vit.gottwald@broadcom.com>
> Fix listing of instances

- CHANGELOG.md
- README.md
- packages/explorer-for-endevor/.prettierignore
- packages/explorer-for-endevor/package.json
- packages/explorer-for-endevor/src/tree/provider.ts
Signed-off-by: Nikolai Imbirev <nikolay.imbirev@broadcom.com>
> 0.13.1 Final release updates

- CHANGELOG.md
- README.md
- packages/explorer-for-endevor/package.json
- packages/explorer-for-endevor/src/commands/edit/common.ts
- packages/explorer-for-endevor/src/extension.ts
- packages/explorer-for-endevor/src/utils.ts
- Fixed the issue that caused the accept/discard change buttons to disappear in the diff editor while saving an edited element.
- Updated the documentation. Changed the old product names to new ones.
> Release 0.14.1

- CHANGELOG.md
- packages/endevor/_doc/Endevor.ts
- packages/explorer-for-endevor/package.json
- packages/explorer-for-endevor/src/commands/uploadElement.ts
- packages/explorer-for-endevor/src/dialogs/locations/endevorUploadLocationDialogs.ts
- packages/explorer-for-endevor/src/element-locations/__tests__/__fixtures__/get-endevor-location-profile/endevor-location/correct-location-profile.yaml
- packages/explorer-for-endevor/src/element-locations/__tests__/__fixtures__/get-endevor-location-profile/endevor-location/endevor-location_meta.yaml
- packages/explorer-for-endevor/src/element-locations/__tests__/__fixtures__/get-endevor-location-profile/endevor-location/profile-with-incorrect-stage.yaml
- packages/explorer-for-endevor/src/element-locations/__tests__/__fixtures__/get-endevor-location-profile/endevor-location/profile-with-wild-env.yaml
- packages/explorer-for-endevor/src/element-locations/__tests__/__fixtures__/get-endevor-location-profile/endevor-location/profile-with-wild-instance.yaml
- packages/explorer-for-endevor/src/element-locations/__tests__/__fixtures__/get-endevor-location-profile/endevor-location/profile-without-env.yaml
- packages/explorer-for-endevor/src/element-locations/__tests__/__fixtures__/get-endevor-location-profile/endevor-location/profile-without-instance.yaml
- packages/explorer-for-endevor/src/element-locations/__tests__/__fixtures__/get-endevor-location-profile/endevor-location/profile-without-stage.yaml
- packages/explorer-for-endevor/src/element-locations/__tests__/elementLocations-test.ts
- packages/explorer-for-endevor/src/element-locations/elementLocations.ts
- packages/explorer-for-endevor/src/tree/endevor.ts
- packages/explorer-for-endevor/src/tree/provider.ts
- packages/vscode-wrapper/_doc/logger.ts
- packages/vscode-wrapper/logger.ts
- yarn.lock
- Fixed an issue that prevented the extension from building an Endevor map tree if lowercased values were used in an Endevor location profile.
- Fixed an issue that caused the extension activation failure in the VSCode version 1.63.2 or lower.
> Release 1.0.2 changes

- CHANGELOG.md
- packages/endevor/__tests__/api-v1-test.ts
- packages/endevor/__tests__/api-v2-test.ts
- packages/endevor/__tests__/ext-test.ts
- packages/endevor/_ext/Endevor.ts
- packages/endevor/endevor.ts
- packages/explorer-for-endevor/package.json
- packages/explorer-for-endevor/src/_doc/telemetry/v2/Telemetry.ts
- packages/explorer-for-endevor/src/commands/sync/confirmConflictResolution.ts
- packages/explorer-for-endevor/src/commands/sync/discardChanges.ts
- packages/explorer-for-endevor/src/commands/sync/initWorkspace.ts
- packages/explorer-for-endevor/src/commands/sync/pullFromEndevor.ts
- packages/explorer-for-endevor/src/commands/sync/revertSectionChange.ts
- packages/explorer-for-endevor/src/commands/sync/syncWorkspace.ts
- packages/explorer-for-endevor/src/constants.ts
- packages/explorer-for-endevor/src/dialogs/scm/conflictResolutionDialogs.ts
- packages/explorer-for-endevor/src/endevor.ts
- packages/explorer-for-endevor/src/store/_doc/Actions.ts
- packages/explorer-for-endevor/src/store/_doc/v2/Store.ts
- packages/explorer-for-endevor/src/store/resolvers.ts
- packages/explorer-for-endevor/src/store/scm/__tests__/workspace-test.ts
- packages/explorer-for-endevor/src/store/scm/_doc/Error.ts
- packages/explorer-for-endevor/src/store/scm/_ext/Workspace.ts
- packages/explorer-for-endevor/src/store/scm/error.ts
- packages/explorer-for-endevor/src/store/scm/utils.ts
- packages/explorer-for-endevor/src/store/scm/workspace.ts
- packages/explorer-for-endevor/src/store/store.ts
- packages/explorer-for-endevor/src/tree/endevor.ts
- packages/explorer-for-endevor/src/tree/provider.ts
- Fixed an issue with collapsing the Endevor tree on refresh.
- Fixed an issue with fetching environments, systems and subsystem outside of the specified Endevor map.
- Improved the Endevor workspace sync related messages.
> 1.3.1 release changes

- CHANGELOG.md
- packages/endevor/__tests__/api-v1-test.ts
- packages/endevor/__tests__/api-v2-test.ts
- packages/endevor/__tests__/ext-test.ts
- packages/endevor/_doc/Endevor.ts
- packages/endevor/_ext/Endevor.ts
- packages/endevor/endevor.ts
- packages/endevor/utils.ts
- packages/explorer-for-endevor/package.json
- packages/explorer-for-endevor/src/_doc/EndevorClient.ts
- packages/explorer-for-endevor/src/store/resolvers.ts
- Fixed an issue with the fetching of Endevor elements for environments where the Stage ID does not correspond to the Stage number.
> 1.3.2 release changes

- CHANGELOG.md
- packages/explorer-for-endevor/package.json
- packages/explorer-for-endevor/src/store/__tests__/store-test.ts
- packages/explorer-for-endevor/src/store/store.ts
- Fixed an issue with the up-the-map view which showed an incomplete list of the elements if the same element name is used for different types.
> 1.4.2 release changes

- .eslintignore
- .prettierignore
- .prettierignore-ci
- combined_coverage_report.sh
- package.json
- packages/endevor/jest.config.js
- packages/explorer-for-endevor/jest.config.js
- packages/explorer-for-endevor/package.json
- packages/profiles/jest.config.js
- packages/type-parser/jest.config.js
- packages/views/jest.config.js
- yarn.lock
Added combined test coverage report generation at each unit test run.
> Add combined test coverage report

- packages/explorer-for-endevor/package.json
- packages/explorer-for-endevor/src/commands/__tests__/editElement.test.ts
- packages/explorer-for-endevor/src/commands/element/editElement.ts
- packages/explorer-for-endevor/src/constants.ts
- packages/explorer-for-endevor/src/extension.ts
- packages/explorer-for-endevor/src/store/__tests__/store-test.ts
- packages/explorer-for-endevor/src/store/_doc/Actions.ts
- packages/explorer-for-endevor/src/store/_doc/v2/Store.ts
- packages/explorer-for-endevor/src/store/store.ts
- packages/explorer-for-endevor/src/utils.ts
> Save edit context between vscode sessions

- packages/explorer-for-endevor/package.json
- packages/explorer-for-endevor/src/commands/addServiceAndLocation.ts
- packages/explorer-for-endevor/src/commands/id.ts
- packages/explorer-for-endevor/src/commands/location/addNewSearchLocation.ts
- packages/explorer-for-endevor/src/commands/service/addNewService.ts
- packages/explorer-for-endevor/src/commands/sync/pullFromEndevor.ts
- packages/explorer-for-endevor/src/commands/sync/syncWorkspace.ts
- packages/explorer-for-endevor/src/extension.ts
- packages/explorer-for-endevor/src/store/__tests__/store-test.ts
- packages/explorer-for-endevor/src/store/_doc/Actions.ts
- packages/explorer-for-endevor/src/store/_doc/v2/Store.ts
- packages/explorer-for-endevor/src/store/scm/_doc/Actions.ts
- packages/explorer-for-endevor/src/store/scm/_doc/Workspace.ts
- packages/explorer-for-endevor/src/store/scm/resolvers.ts
- packages/explorer-for-endevor/src/store/scm/store.ts
- packages/explorer-for-endevor/src/store/store.ts
- packages/explorer-for-endevor/src/store/utils.ts
Store workspace service and location profiles.
Show them on the status bar.
Use Zowe default profiles if available.
> Store workspace sync profiles and show it on vscode status bar
